### PR TITLE
TLUNIZIN-591 used Addressable::URI.escape instead of URI.escape

### PR DESCRIPTION
**Pull request by zqian**

### CODE REVIEW

**Comment by dlhaines** [comment]
Can the reason this matters be documented?  Is it a good idea to recommend that others do the same?

**Comment by zqian** [comment]
Added comments as for why Addressable::URI.escape is selected to replace URI.encode

**Comment by dlhaines** [comment]
Looks good.

**Comment by lsloan** [comment]
I see you've replaced a deprecated function call with an equivalent one.  You've also changed the output format slightly and print the text of an exception (I presume that's what it is, since I don't know Ruby well).  I take it that last point is the purpose behind the title of the JIRA issue, "handle warnings in Ruby verbose output with sis_upload.rb script".  Is that correct?

**Comment by zqian** [comment]
Lance:

I have included the warning inside the TLUNIZIN-519 comment:

"/usr/local/ctools/app/ctupload/bin/sis_upload.rb:95:in `Canvas_API_IMPORT': warning: URI.escape is obsolete"

This is why I switch to another package in order to avoid this error.

**Comment by lsloan** [comment]
Got it.  I didn't search for the JIRA issue before I reviewed the PR.

--
Lance E Sloan, Application Developer
Univ. of Michigan, Info. and Tech. Services - http://www.its.umich.edu/
I'm definitely *not* endorsing specific products.  Honest!

**Comment by zqian** [comment]
I should have included the description into the Pull Request. I will do it
next time.

Thanks,

- Zhen

**Pull request merged**
